enum Colors {
    Green = "green",
    Black = "black",
    Red = "red",

}

export const RouletteResultColor: Record<RouletteResultValue, RouletteResultColor> = {
    0: Colors.Green,
    1: Colors.Black,
    2: Colors.Red,
    3: Colors.Black,
    4: Colors.Red,
    5: Colors.Black,
    6: Colors.Red,
    7: Colors.Black,
    8: Colors.Red,
    9: Colors.Black,
    10: Colors.Red,
    11: Colors.Black,
    12: Colors.Red,
    13: Colors.Black,
    14: Colors.Red,
    15: Colors.Black,
    16: Colors.Red,
    17: Colors.Black,
    18: Colors.Red,
    19: Colors.Black,
    20: Colors.Red,
    21: Colors.Black,
    22: Colors.Red,
    23: Colors.Black,
    24: Colors.Red,
    25: Colors.Black,
    26: Colors.Red,
    27: Colors.Black,
    28: Colors.Red,
    29: Colors.Black,
    30: Colors.Red,
    31: Colors.Black,
    32: Colors.Red,
    33: Colors.Black,
    34: Colors.Red,
    35: Colors.Black,
    36: Colors.Red,
};
